### ISSUE TITLE
Reading a single group/dataset from azure blob storage or s3

### ISSUE THREAD

**Issue by gastoneb** [manzt/zarrita.js#126]
Is this possible? Available examples seem to access public files only.

**Comment by manzt** [comment]
It is definitely possible. From a web browser you'll likely need to access datasets via [HTTP endpoints](https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteEndpoints.html) for object storage. These are generally available to setup on buckets for s3/azure/gcs. You'll need to make you you set up CORs.

If you have some other authentication in mind, you may need to create your own custom store. For example, instead of using the `FetchStore` which uses HTTP requests and is build on the `fetch` API, you could implement your own storage interface for accessing data from a cloud provider. https://manzt.github.io/zarrita.js/packages/storage.html
