### ISSUE TITLE
In README, Comment on relationship with https://github.com/gzuidhof/zarr.js/

### ISSUE THREAD

**Issue by morandd** [manzt/zarrita.js#211]
There's an existing Typescript package for reading Zarr files here https://github.com/gzuidhof/zarr.js/

Presumably this new package has some features or use cases the that package does not cover. Could you comment on the relationship between these two packages? That would help new users (like myself) decide between the two.

**Comment by manzt** [comment]
Hi there. I'm aware of the other project and one of the primary contributors. 

zarr.js is a port of the Python implementation, which led to some inherent design limitations which made it challenging to maintain and introduce new features. In contrast, zarrita.js was a complete rewrite designed for JavaScript with a more functional API, offering better tree-shaking. This allows developers to only include the features they need, potentially reducing bundle sizes. 

zarrita.js also has a more streamlined (and subjectively ergonomic) API, focusing on common use cases rather than mirroring the extensive Python API. 

The primary funcational difference is that **zarrita.js supports both Zarr v2 and v3** (zarr.js only supports v2). Beyond that,  zarrita.js offers a collection of storage backends and improved TypeScript typings.
