### ISSUE TITLE
Unknown codec: bitround

### ISSUE THREAD

**Issue by pelusanchez** [manzt/zarrita.js#233]
First of all, thank you very much for developing this library. It is fast and very well written!

I do not think this is an issue but an enhancement/adding support.

Checking with some Zarr files, I have found the following error:

> Uncaught Error: Unknown codec: bitround

As I see here, it seems that bitround is a codec (maybe is new or it is not implemented for now).

https://github.com/zarr-developers/numcodecs/blob/main/numcodecs/bitround.py

I am not really familiar -for now- with Zarrita source code, but if I have some time and it is welcome, I could try to propose a pull request.

The `.zarray` file of the variable I want to open is like this:

```
{
    "chunks": [
        32,
        32,
        32
    ],
    "compressor": {
        "blocksize": 0,
        "clevel": 9,
        "cname": "zstd",
        "id": "blosc",
        "shuffle": 1
    },
    "dimension_separator": ".",
    "dtype": "<f4",
    "fill_value": "NaN",
    "filters": [
        {
            "id": "bitround",
            "keepbits": 10
        }
    ],
    "order": "C",
    "shape": [
       365,
       1024,
       1024
    ],
    "zarr_format": 2
}
```

Thank you very much,

EDIT: Maybe this issue should be at manzt/numcodecs.js, feel free to move it.

**Comment by manzt** [comment]
Thank you for your feedback and for using the library!

I’ve added read-only support for `bitround` (a no-op since bitround encoding is lossy), which hopefully should work for your data. If you’d like to contribute or need encoding support, it should be straightforward to implement here, following the Python implementation. I’ve held off on implementing it for now to avoid adding unnecessary complexity and maintenance until a clear use case arises.

**Comment by pelusanchez** [comment]
Thank you very much for the fast update! 

I would like if there is some recommended way for extending https://github.com/manzt/zarrita.js/blob/c15c1a14e42a83516972368ac962ebdf56a6dcdb/packages/core/src/codecs.ts#L39 without need to "pollute" the codebase (just in case something like this arises).

Very grateful for your help!
